### ISSUE TITLE
[Epic] Authentication & Proxy

### ISSUE THREAD

**Issue by ghost** [Access-Point-Program/cohort-3-authentication-proxy#1]
This application will be entry point for all other User Interfaces and API endpoints. There will be a User Interface created that will allow a user to login and create an account. The authentication will leverage an API written in Java/SpringBoot. All other application routes will be protected by Authentication cookies to secure the routes. 

### Technologies:

- Java / SpringBoot / Spring Security / Rest Assured / Swagger
- Angular v15 / Typescript / Jasmine
- Selenium / Cucumber
- Docker / Jenkins
- Postgres / SQL
- Python
- Postman

### Team Members

- Joshua Haase
- Owen Starks
- Nick Woodson
- Mason Kuenneke
- Aaron Akridge
- Cameron Brooks

### Requirements:

- 1 Angular / TypeScript application with two pages, login and create an account.
- 1 Java / SpringBoot API
  - 1 POST endpoint for creating an account.
  - 1 POST endpoint for logging in.

### User Stories
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/11
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/12
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/58

### Spikes
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/38
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/23
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/22
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/27
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/25
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/26
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/28
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/37
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/41
- [x] https://github.com/Access-Point-Program/cohort-3-authentication-proxy/issues/43
